# Services definition for running CLI commands

services:

  app:
    # Extend
    extends:
      file: ./docker-compose.yml
      service: app
    # Build override
    image: ${IMAGES_PREFIX:-app}-cli:${IMAGES_TAG:-latest}
    build:
      target: app_cli
      args: !reset []
    # Deploy override
    environment: !reset []
    volumes:
      - ./app/app:/app
      - pnpm:/pnpm
    ports: !reset []

volumes:

  pnpm:
